### ISSUE TITLE
Display issues on a RBS blocks

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/Plugin-RoomBookingSystem#1]
![image](https://user-images.githubusercontent.com/12826304/156750821-9356503a-21ff-4778-98fb-7c9c9c8a26a1.png)

**Comment by RobTrehy** [comment]
This has (kind of) been fixed with the release of version 1.0.1

- Previews have been disabled, as the UI will just never fit into the space available.
- The UI has been updated on the filtering form to fit the page and keep with WebApps styling.

---

If you have updated WebApps to version 1.0.6, you can go to settings and Clear System Cache before checking for Plugin updates.

Otherwise, update availability is cached for 7 days, so you will need to keep checking your Settings > Apps & Plugins page until the update to 1.0.1 for this Plugin becomes available.
